### ISSUE TITLE
Can't open dmg on osx11

### ISSUE THREAD

**Issue by jmmarcus** [Septercius/rpcemu-dev#4]
![cant](https://user-images.githubusercontent.com/65196773/81615305-a8f87000-93e1-11ea-824e-c66a2ea6db56.jpg)
Hello i'am fan user. I can't open the dmg archive on my mac. It's not the first time. The previous version 9.2 mismatch too. I tryed open others dmg archive and i haven't problem.
thank

**Comment by Septercius** [comment]
I think this is because the DMG is in APFS format, not HFS+.  I have rebuilt the 0.9.3a DMGs in HFS+ format, and there are also ZIP files of the release.

**Comment by jmmarcus** [comment]
Thank a lot
