### ISSUE TITLE
Apple Silicon build

### ISSUE THREAD

**Issue by davidpsharp** [Septercius/rpcemu-dev#5]
Hi,
Is there any chance you might release a universal binary that includes an Apple Silicon build of rpcemu? The existing Intel build you released works fine but I suspect battery life would be better with the native buiild. I've attempted to make it myself but haven't made much headway with figuring out how to install the necessary qt modules so I'm wondering if it's something that's super quick for you to do.

**Comment by Septercius** [comment]
I'll have a look and see what I can do over the next week, as I have some free time then.  There may not be too big a gain in the "recompiler" version as the program outputs x86 assembler (it would need to be changed to output ARM/Apple Silicon assembler, which is a bit beyond my abilities).  The "interpreter" version would certainly benefit.

**Comment by davidpsharp** [comment]
That would be great thanks, yes the interpreter version alone would be more than sufficient and very much appreciated!

**Comment by Septercius** [comment]
I've built a version that should work natively under Apple Silicon:

https://github.com/Septercius/rpcemu-dev/releases/tag/0.9.3b

The interpreter version of the emulator is a universal binary for both Intel (x86) and Apple Silicon (arm64).  The recompiler is Intel-only, but will run under Rosetta on Macs with Apple Silicon.

Please try it out and let me know if you find any issues.  Thanks!

**Comment by davidpsharp** [comment]
Thanks so much! I've been using the Interpreter release build on my M1 Macbook Air for a while this evening and seems rock solid so far and approx 10 MIPS faster than the Intel build on Rosetta just sitting at the Desktop (more like 135 MIPs vs 125). I'll keep using it and report back if I see any problems.

**Comment by davidpsharp** [comment]
I tried out the recompiler build out of interest, it's phenomenal that it works at all (Rosetta 2 is really impressive) but would strongly advise against using it on Apple Silicon.

The performance is highly erratic, taking roughly 10x as long to reach the desktop as the Interpreter but then reporting around 200 MIPS resting on the desktop compared to the 135 MIPS on the interpreter. However when you try and do anything e.g. scrolling a filer window it refreshes very slowly (other screen refreshes seem similarly slow) and the MIPS rate drops to single digits frequently (presumably due to Rosetta recompiling newly generated x86 code whenever new code paths are executed) before recovering again. As a result it's all fairly unpleasant usability-wise compared to the silky-smooth interpreter build.

Completely understand if you don't want to bother adding it but this page recommends a quick way to test if the binary is running under Rosetta and the recompiler build could recommend using the interpreter instead: https://developer.apple.com/documentation/apple-silicon/about-the-rosetta-translation-environment

**Comment by Septercius** [comment]
Closing as the interpreter build now works on Apple Silicon, and updating the dynamic recompiler to generate arm64 instructions instead of x86/x64 is way beyond my abilities.
